name: jazzy

on:
  pull_request:
    branches:
      - jazzy
  push:
    branches:
      - jazzy
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:noble
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: jazzy

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.18

      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.8
        with:
          package-name: rosserial_msgs rosserial_server rosserial_stm32
          target-ros2-distro: jazzy

          colcon-defaults: |
            {
              "test": {
                "parallel-workers": 1
              }
            }

          extra-cmake-args: -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage

          coverage-result: true

      - name: Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
